### ISSUE TITLE
This repo is huge. Remove cache and build files from Git?

### ISSUE THREAD

**Issue by vibl** [Ironclad/rivet#134]
### What happened?

This Git repo is huge. It currently weighs 713 MB, with only 16 MB of code and assets.

Most of the size is due to cache and bin directories, and the Git objects (`.git/objects/pack/pack-*.idx`) that version them:

```
.yarn/ 
packages/app-executor/bin/
packages/app-executor/dist/
packages/docs/.yarn/
packages/cli/bin/ 
packages/python/
...
``` 

Is there any use in versioning them?

To remove the extraneous objects from Git:

Command to find them:
```
for hash in $(git verify-pack -v .git/objects/pack/pack-*.idx | sort -k 3 -n | tail -10 | awk '{print $1}'); do git rev-list --all --objects | grep $hash; done

```
Command to remove them safely:
```
git filter-repo --invert-paths --path .yarn/ --path packages/app-executor/bin/  --path packages/app-executor/dist/ --path packages/docs/.yarn/ --path packages/cli/bin/ --path packages/python/ [...]
```
(From https://github.com/newren/git-filter-repo/)

I was able to reduce the repo to 44 M.

You won't have to recommend your users to clone it with `git clone --filter=blob:none` anymore.

**Comment by abrenneke** [comment]
Yeah the main discussion for this is here https://github.com/yarnpkg/berry/discussions/4845

So, this repo follows yarn zero-install (unfortunately it does need a `yarn install` still for a few native deps), but I still like the idea of all the data being download with the one git install, rather than the data needing to be installed via yarn. I know it's a controversial take, but recommending `--filter=blob:none` is a pretty small thing. 

I'd prefer to keep it like this for now, since it's not really hurting anyone.

**Comment by vibl** [comment]
Ok
