### ISSUE TITLE
[Feature]: llama2 support?

### ISSUE THREAD

**Issue by shuhaodo** [Ironclad/rivet#159]
### Feature Request

...Is it possible to support self-hosted LLMs like llama2? Or where is the code point to add this support, I'd love to work on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment]
Hey @shuhaodo I got Llama 2 working locally using the [Oobabooga Plugin](https://github.com/hushaudio/rivet-oobabooga-plugin) for Rivet. Do you use that? Otherwise you could take a look at the [Python Exec Example Plugin](https://github.com/abrenneke/rivet-plugin-example-python-exec) I made as a jumping off point!

**Comment by shuhaodo** [comment]
thanks!

**Comment by abrenneke** [comment]
Can also use [LM Studio](https://lmstudio.ai/)
