### ISSUE TITLE
[Bug]: "JSON strings"

### ISSUE THREAD

**Issue by mindplay-dk** [Ironclad/rivet#307]
### What happened?

I believe I've managed to isolate a fundamental data type issue with JSON values - have a look at this:

![image](https://github.com/Ironclad/rivet/assets/103348/38c1bca7-bcc2-4ef2-9132-6fcb8120a2b9)

as you can see, from top to bottom:

1. A "JSON array" of "JSON strings" converts into a single string with multiple quoted strings.
2. if we split the values, the "JSON strings" individually convert into quoted strings.
3. the "to JSON" node is able to convert a "JSON array" or "JSON strings" back into JSON just fine.

now contrast that example with this one:

![image](https://github.com/Ironclad/rivet/assets/103348/48aa6170-3c32-4209-bf04-ea0e9a267c8e)

as you can see, from top top bottom:

1. a "regular array" of "regular strings" converts into a single string with line-breaks but no quotes.
2. if we split the values, "regular strings" convert into plain strings without any quotes.
3. the "to JSON" node handles "regular strings/arrays" the same as "JSON strings/array".

It looks like this might be a symptom of "leaky" underlying JSON wrapper data types?

Here is the example project for reference: [JSON-strings.zip](https://github.com/Ironclad/rivet/files/13886133/JSON-strings.zip)

### What was the expected functionality?

Strings and arrays should behave the same everywhere.

### Describe your environment

Win 11 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codemile** [comment]
I don't think `Object` knows it's outputting a collection. Technically, in JavaScript an Array is an Object. We use named data types in Rivet (meaning, there is a string representation for that type). As a result, the Text node is just reading that string which says it's an Object type. The output is probably just a side effect of that object being a collection.

This might be easily fixed by having the Object node inspect the data for being an Array and outputting the appropriate type string.

Fyi, I'm just guessing here.

**Comment by mindplay-dk** [comment]
> This might be easily fixed by having the Object node inspect the data for being an Array and outputting the appropriate type string.

You can't inspect the data until there's data though...?

**Comment by abrenneke** [comment]
It's actually because we end up with a type 

```
{
  "type": "object",
  "value": "foo",
}
```

So it's JSON.stringifying the value. I think if we more intelligently format object values this will be improved.
